/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Bhakti
 */

import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.io.FileInputStream;
import java.util.*;
import jxl.Sheet;
import jxl.Workbook;

public class KMean extends javax.swing.JFrame {

    /**
     * Creates new form KMean
     */
    public KMean() {
        initComponents();
    }
    int[] count;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setText("K-Means Clustering");

        jLabel2.setText("Number of Clusters:");

        jButton1.setText("Run");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 29, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here
         try {
             String FilePath = "C:\\Users\\Bhakti\\Downloads\\census.xls";
        FileInputStream fs = new FileInputStream(FilePath);
        Workbook wb = Workbook.getWorkbook(fs);
  // TO get the access to the sheet
         sh = wb.getSheet("Sheet1");
       

        } catch (Exception ex) {
            Logger.getLogger(DM.class.getName()).log(Level.SEVERE, null, ex);
        }
        for(int j=0;j<totalNoOfRows;j++)
        {
            cluster[j]=-1;
        }
      k=Integer.parseInt(jTextField1.getText());
      meanx=new int[k];
      meany=new int[k];
      count=new int[k];
        for(int i=0;i<k;i++){   
            meanx[i]=Integer.parseInt(sh.getCell(colx,rowno).getContents().replaceAll(",",""));
            meany[i]=Integer.parseInt(sh.getCell(coly,rowno).getContents().replaceAll(",",""));
            cluster[rowno]=0;
            rowno++;
        }
        rowno=5;
      for(int numi=0; numi<5; numi++){
           for(int row=5;row<totalNoOfRows-2;row++)
        {
      
             int x=Integer.parseInt(sh.getCell(colx,row).getContents().replaceAll(",",""));
            int y=Integer.parseInt(sh.getCell(coly,row).getContents().replaceAll(",",""));
            int min=-1;
            for(int j=0;j<k;j++)
            {
                //find minimum cost
                int cost=Math.abs(meanx[j]-x)+Math.abs(meany[j]-y);
                if(min==-1)
                {
                    min=cost;
                    cluster[row]=j;
                   
                }
                else if(cost<min)
                {
                min=cost;
                cluster[row]=j;
                }
            }
        }
            for(int j=0;j<k;j++)
            {
                meanx[j]=0;
                meany[j]=0;
                count[j]=0;
            }
           
           for(int row=5;row<totalNoOfRows-2;row++)
        {
            int x=Integer.parseInt(sh.getCell(colx,row).getContents().replaceAll(",",""));
            int y=Integer.parseInt(sh.getCell(coly,row).getContents().replaceAll(",",""));
             meanx[cluster[row]]+=x;
             meany[cluster[row]]+=y;
             count[cluster[row]]++;
            
            }
           for(int j=0;j<k;j++)
            {
                meanx[j]/=count[j];
                meany[j]/=count[j];
            }

      }
      for(int i=0;i<k;i++){
            jTextArea1.append("\nCluster "+(i+1)+" mean: ("+meanx[i]+","+meany[i]+")");
      
        
        jTextArea1.append("\nCluster "+(i+1)+": ");
        for(int j=5;j<totalNoOfRows-2;j++){
            if(cluster[j]==i){
            int x=Integer.parseInt(sh.getCell(colx,j).getContents().replaceAll(",",""));
            int y=Integer.parseInt(sh.getCell(coly,j).getContents().replaceAll(",",""));
            jTextArea1.append("("+x+","+y+") ");
            }
        }
      }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    float sum=0,d,ans;
        //int totalNoOfRows = sh.getRows();
        int totalNoOfRows = 100;
        int cluster[]=new int[totalNoOfRows];
                int costs[]=new int[totalNoOfRows];
        int colx=12,coly=13, k;
          int flag=0;
        int meanx[];
        int meany[];
        int rowno=5;
        long newcost=0;
        long oldcost=0;
        Sheet sh;
 
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KMean.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KMean.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KMean.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KMean.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KMean().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
